### ISSUE TITLE
I guess I can comment here? (My solution)

### ISSUE THREAD

**Issue by javandbeyond** [amazinigmech2418/BrowserCrash#1]
Run this in your browser's console:
document.querySelector('a').click(); //This works the same as clicking by hand
location.href = ''; //This line defuses the bomb in the short time before it explodes

**Comment by amazinigmech2418** [comment]
It doesn't work.

**Comment by javandbeyond** [comment]
If you run it, it doesn't appear to do anything, but if you remove or comment out the location.href line it causes problems.
